# Generated by Django 5.2.14 on 2026-05-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_conversation_conversationmessage_userreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreport",
            name="career_pathways",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="userreport",
            name="problem_solving_style",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
