# Generated by Django 5.2.14 on 2026-05-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0003_userreport_career_pathways_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreport",
            name="exploration_suggestions",
            field=models.JSONField(default=list),
        ),
    ]
